### ISSUE TITLE
moment.js deprecation warning

### ISSUE THREAD

**Issue by jbruni** [dangrossman/bootstrap-daterangepicker#999]
This is appearing at console when I use bootstrap-daterangepicker:

> Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period).
> Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period).

**Comment by dangrossman** [comment]
Fix merged

**Comment by rafaeldruiz** [comment]
I'm still receiving this warning with the last version of daterangepicker.

 * Minified by jsDelivr using Terser v3.14.1.
 * Original file: /npm/daterangepicker@3.0.5/daterangepicker.js

Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.

Any news?

**Comment by dangrossman** [comment]
It was fixed 3 years ago, which is the age of this issue you're commenting on.

Feel free to search the file: https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.js

There are no instances of moment().subtract(period, number) in the code.

**Comment by rafaeldruiz** [comment]
Sorry for my mistake, the error was coming from another plugin.
